import { StyleSheet } from "react-native";

export const colors = {
  ink: "#1c1410",
  paper: "#f3ecdf",
  card: "#fffaf3",
  line: "#e3d5c4",
  brand: "#9d2c2c",
  muted: "#74685d",
  herb: "#1d6844",
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.paper, paddingTop: 52, paddingHorizontal: 16 },
  title: { fontSize: 28, fontWeight: "700", color: colors.ink, textAlign: "right", marginBottom: 12 },
  muted: { color: colors.muted, textAlign: "right", marginBottom: 8 },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
    gap: 6,
  },
  row: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", gap: 8 },
  name: { fontSize: 18, fontWeight: "700", color: colors.ink, textAlign: "right" },
  input: {
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    textAlign: "right",
    color: colors.ink,
  },
  button: { backgroundColor: colors.brand, borderRadius: 12, paddingVertical: 12, paddingHorizontal: 14, alignItems: "center" },
  buttonText: { color: "#fffaf3", fontWeight: "700" },
  ghost: { backgroundColor: "transparent", borderWidth: 1, borderColor: colors.line },
  ghostText: { color: colors.ink, fontWeight: "700" },
  error: { color: colors.brand, textAlign: "right", marginBottom: 8 },
  chipRow: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8, marginBottom: 12 },
  chip: { borderWidth: 1, borderColor: colors.line, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6 },
  chipOn: { backgroundColor: colors.brand, borderColor: colors.brand },
  chipText: { color: colors.ink },
  chipTextOn: { color: "#fff" },
  tabs: {
    flexDirection: "row-reverse",
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: "#1c1410",
    paddingBottom: 18,
    paddingTop: 8,
  },
  tab: { flex: 1, alignItems: "center" },
  tabText: { color: "#f0e6d8", fontSize: 12 },
  tabOn: { color: "#f2c48d", fontWeight: "700" },
});
